name: 'hoop_analytics'
profile: 'hoop_analytics'
version: '1.0.0'
config-version: 2

model-paths: ['models']
seed-paths: ['seeds']
'test-paths': ['tests']
macro-paths: ['macros']

target-path: 'target'
clean-targets: 
  - 'target'
  - 'dbt_packages'

seeds:
  hoop_analytics:
    player_info_overrides:
      +column_types:
        player_id: varchar
        position: varchar
        height: varchar
        weight: integer
        birthdate: date
        school: varchar
        country: varchar
        draft_year: varchar
        draft_round: varchar
        draft_number: varchar

models:
  hoop_analytics:
    staging: 
      +materialized: view
      +schema: staging
    intermediate: 
      +materialized: view
      +schema: staging 
    marts:
      +materialized: table
      +schema: marts


